#!/bin/sh
#
# Start logging
#

case "$1" in
  start)
	# exec main
	;;
  stop)
	# start-stop-daemon -K -q -p /var/run/syslogd.pid
	# start-stop-daemon -K -q -p /var/run/klogd.pid
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
